<?php

namespace CastingBundle\Repository;

/**
 * CastingReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CastingReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
