<?php

namespace CastingBundle\Repository;

/**
 * ReponseVideoCastingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseVideoCastingRepository extends \Doctrine\ORM\EntityRepository
{
}
