<?php

namespace CastingBundle\Repository;

/**
 * ResponseCastingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseCastingRepository extends \Doctrine\ORM\EntityRepository
{
}
