<?php

namespace CastingBundle\Repository;

/**
 * VideoCastingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoCastingRepository extends \Doctrine\ORM\EntityRepository
{
}
