version: "3.1"
services:
  nginx:
    image: nginx:alpine
    container_name: vipcrossing-nginx
    working_dir: /var/www/vipcrossing
    tty: true
    ports:
      - 800:80
    volumes:
      - ./:/var/www/vipcrossing
      - ./phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  php-fpm:
    build: phpdocker/php-fpm
    container_name: vipcrossing-php-fpm
    working_dir: /var/www/vipcrossing
    volumes:
      - ./:/var/www/vipcrossing
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - app
      - mysql_app

networks:
  app:
  mysql_app:
    external: true
