<?php

namespace Corona\EndBundle\Repository;

/**
 * NbrCoronaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbrCoronaRepository extends \Doctrine\ORM\EntityRepository
{
}
