imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@FrontBundle/Resources/config/services.yml" }
    - { resource: "@BackBundle/Resources/config/services.yml" }
    - { resource: "@MembreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    foo: bar  
    published: true
    default_page: 1
    locale: fr
    upload_dir: '%kernel.root_dir%/../web/upload'
    magazine_dir: '%kernel.root_dir%/../web/'
    upload_Url: 'https://vipcrossing.com/upload/'
    thumb_url: 'https://vipcrossing.com/'
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    auto_reload: "%kernel.debug%"
    cache: '%kernel.cache_dir%/twig'
    optimizations: -1
    globals:
       path_picture: %upload_Url%
       path_no_image: %thumb_url%
       thumb_url_image_banner_back: "%thumb_url%media/cache/image_banner_back/upload/"
       thumb_url_image_index_front: "%thumb_url%media/cache/image_index_front/upload/"
       thumb_url_image_gallerie_front: "%thumb_url%media/cache/image_gallerie_front/upload/"
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                Rand: BackBundle\DQL\RandFunction
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#assetic

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

#fos-user
#fos-user
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
            address: vipcrossingreset@laschekina.com
            sender_name: vipcrossingreset
    service:
            mailer: fos_user.mailer.twig_swift
    registration:
            form:
                type: UserBundle\Form\Type\RegistrationFormType
    profile:
            form:
                type: UserBundle\Form\Type\ProfileFormType

    resetting:
             form:
                     type: UserBundle\Form\Type\ResettingFormType

             token_ttl: 86400
             email:
                        template:   MembreBundle:Resetting:email.html.twig
                        from_email:
                            address:        vipcrossingreset@laschekina.com
                            sender_name:    vipcrossingreset


liip_imagine:
    loaders:
      default:
          filesystem:
               data_root:  "%kernel.root_dir%/../web"
    resolvers:
       default:
          web_path:
            web_root:  "%kernel.root_dir%/../web"
            cache_prefix: media/cache
    cache: default
    filter_sets:

        image_banner_back:
                    data_loader: default
                    quality: 60
                    filters:
                        thumbnail: { size: [282 , 137], mode: outbound }
                        strip: ~
                        interlace:
                            mode: line
        image_index_front:
                    data_loader: default
                    quality: 60
                    filters:
                        thumbnail: { size: [190,190], mode: outbound }
                        strip: ~
                        interlace:
                            mode: line
        image_gallerie_front:
                    data_loader: default
                    quality: 60
                    filters:
                        thumbnail: { size: [225 , 335], mode: outbound }
                        strip: ~
                        interlace:
                            mode: line