front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

casting:
    resource: "@CastingBundle/Resources/config/routing.yml"
    prefix:   /

membre:
    resource: "@MembreBundle/Resources/config/routing.yml"
    prefix:   /

back_questions:
    resource: "@BackBundle/Controller/QuestionsController.php"
    type:     annotation

corona_end:
    resource: "@CoronaEndBundle/Resources/config/routing.yml"
    prefix:   /

magazine:
    resource: "@MagazineBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
