security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PRO:         ROLE_PRO
        ROLE_VIP:         ROLE_VIP
        ROLE_MEMBRE:      ROLE_MEMBRE
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:               fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path:    /redirect_after_login
                always_use_default_target_path: true
                login_path:             fos_user_security_login
                use_forward:            false
                check_path:             fos_user_security_check

            remember_me:
                secret:   "%secret%"
                lifetime: 2592000
                path:     /
                domain:   ~

            logout:       true
            anonymous:    true
    access_denied_url: access_denied
    access_control:
        - { path: ^/admin/medias/editt, role: [ROLE_PRO,ROLE_SUPER_ADMIN] }
        - { path: ^/admin/medias/new, role: [ROLE_PRO,ROLE_SUPER_ADMIN] }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espace-member, role: [ROLE_PRO , ROLE_VIP , ROLE_MEMBRE] }
        - { path: ^/espace-casting, role: [ROLE_PRO , ROLE_VIP] }