personnage_index:
    path:     /
    defaults: { _controller: "BackBundle:Personnage:index" }
    methods:  GET

personnage_new:
    path:     /new
    defaults: { _controller: "BackBundle:Personnage:new" }
    methods:  [GET, POST]

personnage_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Personnage:edit" }
    methods:  [GET, POST]

personnage_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Personnage:delete" }
    methods:  [GET, POST]
