<?php

namespace BackBundle\Repository;

/**
 * ArchetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchetypeRepository extends \Doctrine\ORM\EntityRepository
{
}
