<?php

namespace BackBundle\Repository;

/**
 * BookImagesBDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookImagesBDRepository extends \Doctrine\ORM\EntityRepository
{





    public function getscrollInfini ( $count     )
    {
         $sql = $this->createQueryBuilder ( 'm' )
            ->select(  'm')
              ->where ( "m.showPageHome = 1" )
                ->orderBy ( 'm.id' , 'DESC' )
            ->setMaxResults ( $count )
        ;
        return $sql->getQuery ()->getResult  ();
    }


    public function getscrollInfiniAjax ( $lastId , $count     )
    {
         $sql = $this->createQueryBuilder ( 'm' )
            ->select(  'm')
            ->where ( "m.showPageHome = 1" )
            ->andWhere ( "m.id < :lastId" )

            ->setParameter ( 'lastId' , $lastId )
            ->orderBy ( 'm.id' , 'DESC' )
            ->setMaxResults ( $count )
        ;
        return $sql->getQuery ()->getResult  ();
    }


}
