<?php

namespace BackBundle\Repository;

/**
 * BookVotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookVotesRepository extends \Doctrine\ORM\EntityRepository
{
}
