<?php

namespace BackBundle\Repository;

/**
 * CommentaireMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
