<?php

namespace BackBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getContent($type,$languge)
    {
        $sql = $this->createQueryBuilder('c')
            ->select('c')
            ->innerJoin('c.contenttype', 't')
            ->where("t.title = :type")
            ->andWhere("c.languge = :languge")
            ->setParameter('type', $type)
            ->setParameter('languge', $languge);
        return $sql->getQuery()->getSingleResult();

    }

    public function getContentList($type)
    {
        $sql = $this->createQueryBuilder('c')
            ->select('c')
            ->innerJoin('c.contenttype', 't')
            ->where("t.title = :type")
            ->setParameter('type', $type);

        return $sql->getQuery()->getResult();

    }
}
