<?php

namespace BackBundle\Repository;

/**
 * CrawlerspectacleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerspectacleRepository extends \Doctrine\ORM\EntityRepository
{
    /********* requete Search   ***********/

    public function getSearchWord($searchWord , $language )
    {
        return $this->createQueryBuilder ( 'c' )
            ->addSelect ( 'c' )
            ->where ( "c.title LIKE :searchWord" )
            ->andWhere ( "c.pays LIKE :language" )
            ->orWhere ( "c.shortdescription LIKE :searchWord" )
            ->orWhere ( "c.description LIKE :searchWord" )
            ->orWhere ( "c.channel LIKE :searchWord" )
            ->setParameter('searchWord', '%'.$searchWord.'%')
            ->setParameter('language', $language)
            ->orderBy ( 'c.id' , 'DESC' )
            ->getQuery ()
            ->getResult ();
    }
}
