<?php

namespace BackBundle\Repository;

/**
 * CrosswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrosswordRepository extends \Doctrine\ORM\EntityRepository
{
}
