<?php

namespace BackBundle\Repository;

/**
 * HumeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTypeHumeur ( $userCourant    )
    {
        $sql = $this->createQueryBuilder ( 'b' )
            ->select ( 'b.type' )

            ->where  ( "b.member = :userCourant" )
            ->setParameter ( 'userCourant' , $userCourant )  ;
        return $sql->getQuery ()->getArrayResult  ();
    }

}
