<?php

namespace BackBundle\Repository;

/**
 * LikeMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
