<?php

namespace BackBundle\Repository;

/**
 * ListeDatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeDatesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDateMedia ( $id  )
    {
        $date = new \DateTime();

        $sql = $this->createQueryBuilder ( 'd' )
            ->select ( 'd' )
            ->innerJoin ( 'd.media' , 'm' )

            ->where ( "m.id = :idMedia" )
            ->andWhere(" d.startDate = :startdate   ")
          //  ->andWhere(" d.endDate >= :startdate  ")

            ->setParameter ( 'startdate' , $date )
            ->setParameter ( 'idMedia' , $id )
            ->orderBy ( 'd.startDate' , 'ASC' )
        ;
        return $sql->getQuery ()->getResult ();


    }

    public function getDateMediaCourant ( $id  )
    {
        $date = new \DateTime();

        $sql = $this->createQueryBuilder ( 'd' )
            ->select ( 'd' )
            ->innerJoin ( 'd.media' , 'm' )

            ->where ( "m.id = :idMedia" )
            ->andWhere(" d.startDate <= :startdate   ")
            ->andWhere(" d.endDate >= :startdate   ")
          //  ->andWhere(" d.endDate >= :startdate  ")

            ->setParameter ( 'startdate' , $date )
            ->setParameter ( 'idMedia' , $id )
            ->orderBy ( 'd.startDate' , 'ASC' )
        ;
        return $sql->getQuery ()->getResult ();


    }

    public function getDateMediaFuteur ( $id  )
    {
        $date = date ( "Y-m-d" );
        $date1 = str_replace('-', '/', $date);
        $maDate = date('Y-m-d',strtotime($date . "+15 days"));

        $sql = $this->createQueryBuilder ( 'd' )
            ->select ( 'd' )
            ->innerJoin ( 'd.media' , 'm' )

            ->where ( "m.id = :idMedia" )
            ->andWhere(" d.startDate > :startdate   ")
          //  ->andWhere(" d.endDate >= :startdate  ")

            ->setParameter ( 'startdate' , $date )
            ->setParameter ( 'idMedia' , $id )
            ->orderBy ( 'd.startDate' , 'ASC' )
        ;
        return $sql->getQuery ()->getResult ();


    }
}
