<?php

namespace BackBundle\Repository;

/**
 * ListamisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListamisRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListeAmis ( $membre , $userCourant  )
    {
        $sql = $this->createQueryBuilder ( 'a' )
            ->where ( "a.userReceiver = :userCourant or a.userEmitter = :userCourant " )
            ->andWhere("a.userReceiver = :userMembre or a.userEmitter = :userMembre " )
                  ->setParameter ( 'userCourant' , $userCourant )
            ->setParameter ( 'userMembre' , $membre )
            ;
        return $sql->getQuery ()->getResult();
    }
  public function ListCoupleAmis ( $membre  )
    {
        $sql = $this->createQueryBuilder ( 'a' )
            ->where("a.userReceiver = :userMembre or a.userEmitter = :userMembre " )
            ->setParameter ( 'userMembre' , $membre )
            ;
        return $sql->getQuery ()->getResult();
    }
 public function ListCoupleAmisMessage ( $membre  )
    {
        $sql = $this->createQueryBuilder ( 'a' )
            ->where("a.userReceiver = :userMembre or a.userEmitter = :userMembre " )
            ->setParameter ( 'userMembre' , $membre )
            ;
        return $sql->getQuery ()->getResult();
    }
}
