<?php

namespace BackBundle\Repository;

/**
 * MagazinegalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazinegalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGalleryListVip (  $ListVip )
    {
        $sql = $this->createQueryBuilder ( 'm' )
            ->select ( 'm' )
            ->addSelect ( 'RAND() as HIDDEN rand ' )
            ->innerJoin('m.usercreate', 'u')
            
            ->where ( "m.typegallerys LIKE  'vip" )
            ->where ( "m.state = 1" )
            ->andWhere ( "u.id IN (:ListIdVip)" )

            ->setParameter ( 'ListIdVip' , $ListVip )
       
            ->orderBy ( 'rand' )
        ;
        return $sql->getQuery ()->getResult ();

    }

}
