<?php

namespace BackBundle\Repository;

/**
 * MessagingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagingRepository extends \Doctrine\ORM\EntityRepository
{
    /** Get number Message Not Seen **/
    public function CountMessageNotSeen ( $userCourant , $enable  )
    {
        $sql = $this->createQueryBuilder ( 'm' )
            ->select('count(m.id)')
            ->where ( "m.userreceiver = :userCourant " )
            ->andWhere("m.enable = :enable")
            ->andWhere("m.deleteenable = 0")
            ->setParameter ( 'userCourant' , $userCourant )
            ->setParameter ( 'enable' , $enable );

        return $sql->getQuery ()->getSingleScalarResult();
    }
  /** Get Liste message remove **/
    public function ListeMessageRemove ( $userCourant   )
    {
        $sql = $this->createQueryBuilder ( 'm' )
            ->select('m')
            ->where ( "m.userreceiver = :userCourant  Or m.useremitter = :userCourant " )
            ->andWhere("m.deleteenable = 1")
            ->setParameter ( 'userCourant' , $userCourant )
            ->orderBy ( 'm.dateofsending' , 'desc' ) ;

        return $sql->getQuery ()->getResult();
    }

}
