<?php

namespace BackBundle\Repository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{

      /** Get Vip **/
      public function getIdBook ( $userCourant   )
      {
          $sql = $this->createQueryBuilder ( 'p' )
              ->select('b.id')
              ->innerJoin ( 'p.book' , 'b' )
              ->where ( "p.user = :userCourant" )
              ->setParameter ( 'userCourant' , $userCourant )
              ->orderBy ( 'p.dateCreate' , 'desc' );
          return $sql->getQuery ()->getArrayResult ();
      }
   /** Get Vip **/
   public function getListBook ( $userCourant   )
   {
       $sql = $this->createQueryBuilder ( 'p' )
           ->select('b')
           ->innerJoin ( 'p.book' , 'b' )
           ->where ( "p.user = :userCourant" )
           ->setParameter ( 'userCourant' , $userCourant )
           ->orderBy ( 'p.dateCreate' , 'desc' );
       return $sql->getQuery ()->getResult ();
   }
}
