<?php

namespace BackBundle\Repository;

/**
 * PersonnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnageRepository extends \Doctrine\ORM\EntityRepository
{
    /********* requete get Media acteurs     ***********/
    public function getListeacteur( $idMedia )
    {
        $sql = $this->createQueryBuilder('u')
            ->select('u')
            ->innerJoin('u.medias', 'md')
            ->where("md.id = :idMedia")
            ->setParameter('idMedia', $idMedia);
        return $sql->getQuery()->getResult();
    }
  public function getTweeteracteur( $idMedia )
    {
        $sql = $this->createQueryBuilder('u')
            ->select('u.twitter')
            ->innerJoin('u.medias', 'md')
            ->where("md.id = :idMedia")
            ->andWhere ("u.twitter  IS NOT NULL")
            ->setParameter('idMedia', $idMedia);
        return $sql->getQuery()->getResult();
    }

}
