<?php

namespace BackBundle\Repository;

/**
 * RadioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioRepository extends \Doctrine\ORM\EntityRepository
{
}
