<?php

namespace BackBundle\Repository;

/**
 * ReferancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferancementRepository extends \Doctrine\ORM\EntityRepository
{
}
