<?php

namespace BackBundle\Repository;

/**
 * TypegalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypegalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
