<?php

namespace BackBundle\Repository;

/**
 * TypeContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContentRepository extends \Doctrine\ORM\EntityRepository
{
}
