<?php

namespace BackBundle\Repository;

/**
 * TypeContentMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContentMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
