<?php

namespace BackBundle\Repository;

/**
 * VodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodRepository extends \Doctrine\ORM\EntityRepository
{
}
